# .github/labeler.yml
# Example: Automatically apply labels like 'tests', 'database', 'telegram-bot', etc. based on file paths.
tests/**:
    - tests
database/**:
    - database
telegram_bot/**:
    - telegram-bot
scrapers/**:
    - scraper
utils/**:
    - utils
