# Automatically mark issues and pull requests as stale if no activity is detected.
daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
    - "pinned"
    - "security"
markComment: >
    This issue has been automatically marked as stale because it has not had recent activity.
    It will be closed in 7 days if no further activity occurs.
closeComment: >
    Closing this issue due to inactivity.
