pull_request_rules:
    - name: Automatic merge when CI passes and approved
      conditions:
          - status-success=CI
          - "#approved-reviews-by>=1"
          - "label=automerge"
      actions:
          merge:
              method: merge
