import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_GROUP_ID = os.getenv("TELEGRAM_GROUP_ID")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SCRAPE_INTERVAL = int(os.getenv("SCRAPE_INTERVAL", 600))
DATABASE_URL = os.getenv("DATABASE_URL")
REDIS_URL = os.getenv("REDIS_URL")
