version: "3.8"

services:
    app:
        build: .
        container_name: teslalarm-kr_app
        env_file: .env
        depends_on:
            - db
            - redis
        restart: always

    db:
        image: postgres:17
        container_name: test_database
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: test_database
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always

    redis:
        image: redis:7-alpine
        container_name: teslalarm-kr_redis
        volumes:
            - redisdata:/data
        restart: always

volumes:
    pgdata:
    redisdata:
