name: CI Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.13"]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Poetry
              uses: abatilo/actions-poetry@v4

            - name: Cache Poetry packages
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pypoetry
                  key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              run: poetry install --no-root

            - name: Run tests
              run: poetry run pytest --maxfail=1 --disable-warnings -q

            - name: Upload Coverage Report
              if: always()
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
